FROM node:20-alpine AS Builder
WORKDIR /app
COPY package*.json /app
RUN npm install
COPY . .

FROM  node:20-alpine
WORKDIR /app
COPY --from=builder /app /app
RUN npm prune --production
EXPOSE 4000
CMD [ "node" ,"index.js"] 

