name: Backend CI

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - service: auth-service
            hook: https://api.render.com/deploy/srv-d6etskrh46gs738e99mg?key=aKpVVKtClIY
          - service: session-service
            hook: https://api.render.com/deploy/srv-d6eunvrh46gs73ae7jug?key=sanXXfrckXE
          - service: podcast-service
            hook: https://api.render.com/deploy/srv-d6eu358gjchc73abdlq0?key=S8yB8NOR7bI
          - service: api-gateway
            hook: https://api.render.com/deploy/srv-d6euq208tnhs73bjko30?key=Kv3wze0RNGE

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        working-directory: reverside/services/${{ matrix.service }}
        run: npm install

      - name: Run tests
        working-directory: reverside/services/${{ matrix.service }}
        env:
          AUTH_SERVICE: http://localhost:4001
          SESSION_SERVICE: http://localhost:4003
          PODCAST_SERVICE: http://localhost:4002
          MONGO_URL: mongodb://localhost:27017/test
        run: npm test

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/${{ matrix.service }}:latest ./reverside/services/${{ matrix.service }}

      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/${{ matrix.service }}:latest

      - name: Trigger Render Deploy
        run: |
          curl -X POST ${{ secrets[matrix.hook] }}